//
// File generated by HDevelop for HALCON/.NET (C#) Version 17.12
//

using HalconDotNet;

public partial class HDevelopExport
{
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
  public HDevelopExport()
  {
    // Default settings used in HDevelop 
    HOperatorSet.SetSystem("width", 512);
    HOperatorSet.SetSystem("height", 512);
    if (HalconAPI.isWindows)
      HOperatorSet.SetSystem("use_window_thread","true");
    action();
  }
#endif

#if !NO_EXPORT_MAIN
  // Main procedure 
  private void action()
  {


    // Local iconic variables 

    HObject ho_Code12801, ho_SymbolRegions;

    // Local control variables 

    HTuple hv_WindowHandle = null, hv_BarCodeHandle = null;
    HTuple hv_DecodedDataStrings = null, hv_Row1 = null, hv_Column1 = null;
    HTuple hv_Row2 = null, hv_Column2 = null;
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_Code12801);
    HOperatorSet.GenEmptyObj(out ho_SymbolRegions);
    ho_Code12801.Dispose();
    HOperatorSet.ReadImage(out ho_Code12801, "C:/Users/夏目家的猫/Desktop/code12801.png");
    HOperatorSet.SetWindowAttr("background_color","black");
    HOperatorSet.OpenWindow(0,0,512,512,0,"visible","",out hv_WindowHandle);
    HDevWindowStack.Push(hv_WindowHandle);
    if (HDevWindowStack.IsOpen())
    {
      HOperatorSet.SetPart(HDevWindowStack.GetActive(), 0, 0, 511, 511);
    }
    //创建条码模型
    HOperatorSet.CreateBarCodeModel(new HTuple(), new HTuple(), out hv_BarCodeHandle);
    //识别条码
    ho_SymbolRegions.Dispose();
    HOperatorSet.FindBarCode(ho_Code12801, out ho_SymbolRegions, hv_BarCodeHandle, 
        "auto", out hv_DecodedDataStrings);
    HOperatorSet.SmallestRectangle1(ho_SymbolRegions, out hv_Row1, out hv_Column1, 
        out hv_Row2, out hv_Column2);
    //显示
    if (HDevWindowStack.IsOpen())
    {
      HOperatorSet.SetDraw(HDevWindowStack.GetActive(), "margin");
    }
    if (HDevWindowStack.IsOpen())
    {
      HOperatorSet.SetLineWidth(HDevWindowStack.GetActive(), 3);
    }
    if (HDevWindowStack.IsOpen())
    {
      HOperatorSet.DispObj(ho_Code12801, HDevWindowStack.GetActive());
    }
    if (HDevWindowStack.IsOpen())
    {
      HOperatorSet.DispObj(ho_SymbolRegions, HDevWindowStack.GetActive());
    }
    if (HDevWindowStack.IsOpen())
    {
      HOperatorSet.DispText(HDevWindowStack.GetActive(), hv_DecodedDataStrings, "image", 
          hv_Row2, hv_Column1, "black", new HTuple(), new HTuple());
    }
    //清除模型
    HOperatorSet.ClearBarCodeModel(hv_BarCodeHandle);
    ho_Code12801.Dispose();
    ho_SymbolRegions.Dispose();

  }

#endif


}
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
public class HDevelopExportApp
{
  static void Main(string[] args)
  {
    new HDevelopExport();
  }
}
#endif

