//
// File generated by HDevelop for HALCON/.NET (C#) Version 17.12
//

using HalconDotNet;

public partial class HDevelopExport
{
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
  public HDevelopExport()
  {
    // Default settings used in HDevelop 
    HOperatorSet.SetSystem("width", 512);
    HOperatorSet.SetSystem("height", 512);
    if (HalconAPI.isWindows)
      HOperatorSet.SetSystem("use_window_thread","true");
    action();
  }
#endif

#if !NO_EXPORT_MAIN
  // Main procedure 
  private void action()
  {


    // Local iconic variables 

    HObject ho_Pellets, ho_Regions, ho_RegionErosion;
    HObject ho_ConnectedRegions, ho_RegionDilation, ho_SelectedRegions;

    // Local control variables 

    HTuple hv_Number = null;
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_Pellets);
    HOperatorSet.GenEmptyObj(out ho_Regions);
    HOperatorSet.GenEmptyObj(out ho_RegionErosion);
    HOperatorSet.GenEmptyObj(out ho_ConnectedRegions);
    HOperatorSet.GenEmptyObj(out ho_RegionDilation);
    HOperatorSet.GenEmptyObj(out ho_SelectedRegions);
    ho_Pellets.Dispose();
    HOperatorSet.ReadImage(out ho_Pellets, "C:/Users/夏目家的猫/Desktop/新建文件夹 (2)/pellets.png");
    ho_Regions.Dispose();
    HOperatorSet.Threshold(ho_Pellets, out ho_Regions, 104, 204);
    ho_RegionErosion.Dispose();
    HOperatorSet.ErosionCircle(ho_Regions, out ho_RegionErosion, 9);
    ho_ConnectedRegions.Dispose();
    HOperatorSet.Connection(ho_RegionErosion, out ho_ConnectedRegions);
    ho_RegionDilation.Dispose();
    HOperatorSet.DilationCircle(ho_ConnectedRegions, out ho_RegionDilation, 9);
    ho_SelectedRegions.Dispose();
    HOperatorSet.SelectShape(ho_RegionDilation, out ho_SelectedRegions, (new HTuple("column1")).TupleConcat(
        "area"), "and", (new HTuple(15.97)).TupleConcat(798.36), (new HTuple(500)).TupleConcat(
        5000));
    HOperatorSet.CountObj(ho_SelectedRegions, out hv_Number);
    if (HDevWindowStack.IsOpen())
    {
      HOperatorSet.DispText(HDevWindowStack.GetActive(), ("气弹的个数是："+hv_Number)+"个", 
          "window", "top", "left", "black", new HTuple(), new HTuple());
    }
    //
    if (HDevWindowStack.IsOpen())
    {
      HOperatorSet.ClearWindow(HDevWindowStack.GetActive());
    }
    //
    ho_Pellets.Dispose();
    ho_Regions.Dispose();
    ho_RegionErosion.Dispose();
    ho_ConnectedRegions.Dispose();
    ho_RegionDilation.Dispose();
    ho_SelectedRegions.Dispose();

  }

#endif


}
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
public class HDevelopExportApp
{
  static void Main(string[] args)
  {
    new HDevelopExport();
  }
}
#endif

